# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "nerjs"
    labels:
      - "dependencies"
      - "bot"
      - "cargo"
    target-branch: "dependencies"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "nerjs"
    labels:
      - "dependencies"
      - "bot"
      - "npm"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    groups:
      tailwindcss:
        patterns:
          - "@tailwindcss/cli"
          - "tailwindcss"
